# basic
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: https://en.gravatar.com/userimage/4399767/6eae4865bc149372c2fa46148fc84a4a.jpg?size=200
banner_small: images/banner-small.png
banner_large: images/banner-large.png

# disqus
disqus_shortname: mikedeboernl

# social
social:
  github: https://github.com/mikedeboer
  twitter: https://twitter.com/mikedeboer
  linkedin: https://nl.linkedin.com/in/mikedeboer

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
